# Nome da Aplicação
spring.application.name=payment-ingestion

# ===============================
# Configurações do Banco (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/paysync_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# O Hibernate vai criar as tabelas automaticamente para nós (útil em dev)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# Configurações de Fila (RabbitMQ)
# ===============================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest